add_newline = true

# ----------------------------------------------------
# format
# ----------------------------------------------------
format = """
${custom.directory}\
$git_branch\
$git_status\
$python\
$aws\
$fill\
$cmd_duration\
$time\
\n$character\
"""

[directory]
disabled = true

[custom.directory]
command = "bash ~/.config/zsh/scripts/starship_directory.sh"
when = "true"
format = "$output"

[git_branch]
symbol = ""
style = "bold fg:#7aa2f7 bg:#1f2335"
format = "[](fg:#1f2335)[$symbol $branch ]($style)"

[git_status]
style = "bold fg:#f7768e bg:#1f2335"
format = "[$all_status$ahead_behind]($style)[](fg:#1f2335) "

[cmd_duration]
min_time = 2000
style = 'fg:#e0af68'
format = "[](fg:#e0af68)[󱎫 $duration](fg:#1a1b26 bg:#e0af68)[](fg:#e0af68) "

[time]
disabled = false
time_format = "%R"
format = "[](fg:#1f2335)[ $time](fg:#a9b1d6 bg:#1f2335)[](fg:#1f2335)"

[character]
vimcmd_symbol = '[V](bold green) '

[aws]
format = '[$symbol $profile ]($style)'
symbol = "💭"
style = "bold fg:#ffcb6b"
