add_newline = true

# ----------------------------------------------------
# format
# ----------------------------------------------------
format = """
${custom.directory}\
$git_branch\
$git_status\
$python\
$aws\
$fill\
$cmd_duration\
$time\
\n$character\
"""

[fill]
symbol = " "

[directory]
disabled = true

[custom.directory]
command = "bash ~/.config/zsh/scripts/starship_directory.sh"
when = "true"
format = "$output"

[git_branch]
symbol = ""
style = "bold fg:#cba6f7 bg:#313244" # Mauve on Surface0
format = "[](fg:#313244)[$symbol $branch ]($style)"

[git_status]
style = "bold fg:#f38ba8 bg:#313244" # Red on Surface0
format = "[$all_status$ahead_behind]($style)[](fg:#313244) "

[cmd_duration]
min_time = 2000
style = 'fg:#fab387' # Peach
format = "[](fg:#fab387)[󱎫 $duration](fg:#11111b bg:#fab387)[](fg:#fab387) "

[time]
disabled = false
time_format = "%R"
format = "[](fg:#313244)[ $time](fg:#89b4fa bg:#313244)[](fg:#313244)"

[character]
vimcmd_symbol = '[V](bold green) '

[aws]
format = '[$symbol $profile ]($style)'
symbol = "💭"
style = "bold fg:#ffcb6b"
